<?php
/**
 * Copyright (c) 2020. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 * Morbi non lorem porttitor neque feugiat blandit. Ut vitae ipsum eget quam lacinia accumsan.
 * Etiam sed turpis ac ipsum condimentum fringilla. Maecenas magna.
 * Proin dapibus sapien vel ante. Aliquam erat volutpat. Pellentesque sagittis ligula eget metus.
 * Vestibulum commodo. Ut rhoncus gravida arcu.
 */

// GENERATED by bump_version
return [
    'master_branch' => 'master',
    'develop_branch' => 'dev',
    'version_file' => __DIR__ . '/VERSION',
    'changelog_file' => __DIR__ . '/CHANGELOG', // A basic CHANGELOG
    'release_branches' => ['hotfix' => 'hotfix-*', 'release' => 'release-*']// The branches you should release on
];