#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
Dotenv\Dotenv::createImmutable(__DIR__)->load();

use App\Console\Anime\Get;
use App\Console\Anime\Ongoing\WhenEpisode;
use App\Console\Anime\Status\Update;
use DI\Container;
use Symfony\Component\Console\Application;

$application = new Application();

$container = new Container();
require __DIR__ . '/src/dependencies.php';

$application->add( new Get($container) );
$application->add( new Update($container) );
$application->add( new WhenEpisode($container));

$application->add( new \App\Console\Video\Get($container) );

$application->run();