#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
Dotenv\Dotenv::createImmutable(__DIR__)->load();

use App\Console\GetAnimes;
use App\Console\GetVideos;
use DI\Container;
use Symfony\Component\Console\Application;

$application = new Application();

$container = new Container();
require __DIR__ . '/src/dependencies.php';

$application->add( new GetAnimes($container) );
$application->add( new GetVideos($container) );

$application->run();