#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
Dotenv\Dotenv::createImmutable(__DIR__)->load();

use App\Console\Anime\Episode\UpdateLastEpisode;
use App\Console\Anime\Fix;
use App\Console\Anime\Get;
use App\Console\Anime\Ongoing\WhenEpisode;
use App\Console\Anime\Status\Update;
use App\Console\UpdateDatabase;
use App\Console\Video\Project\ProjectFindVideos;
use App\Console\Video\Project\UpdateFullTranslate;
use DI\Container;
use Symfony\Component\Console\Application;

$application = new Application();

$container = new Container();
require __DIR__ . '/src/dependencies.php';

$application->add( new Get($container) );
$application->add( new Update($container) );
$application->add( new WhenEpisode($container));
$application->add( new \App\Console\Anime\Poster\Get($container));
$application->add( new UpdateLastEpisode($container));
$application->add(new Fix($container));
$application->add(new \App\Console\Anime\Episode\SetNames($container));

$application->add( new \App\Console\Video\Get($container) );
$application->add( new UpdateFullTranslate($container));
$application->add(new ProjectFindVideos($container));
$application->add(new \App\Console\Binary\Download($container));
$application->add(new \App\Console\Binary\Delete($container));
$application->add(new \App\Console\Binary\BatchDownload($container));
$application->add( new \App\Console\User\GetUserRates($container));

$application->add( new UpdateDatabase($container));

$application->run();