name: PHP Composer

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate
    
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy
      uses: musps/action-deployer-php@master
      with:
        args: deploy prod --parallel --limit 2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
